---
- name: Install Git, MySQL, Nginx, NodeJS, NPM
  hosts: all
  become_user: root
  become_method: sudo
  become: true

  roles:
    - common
    - git
    - mysql
    - nginx
    - letsencrypt
    - growlerfriday
